import { createSlice } from "@reduxjs/toolkit";

const locations = {
  title: '위치 선택',
  selected: '한국',
  contents: [
    { id: 0, location: '가나', isSelected: false },
    { id: 1, location: '과테말라', isSelected: false },
    { id: 2, location: '그루지아', isSelected: false },
    { id: 3, location: '그리스', isSelected: false },
    { id: 4, location: '나이지리아', isSelected: false },
    { id: 5, location: '남아프리카', isSelected: false },
    { id: 6, location: '네덜란드', isSelected: false },
    { id: 7, location: '네팔', isSelected: false },
    { id: 8, location: '노르웨이', isSelected: false },
    { id: 9, location: '뉴질랜드', isSelected: false },
    { id: 10, location: '니카라과', isSelected: false },
    { id: 11, location: '대만', isSelected: false },
    { id: 12, location: '덴마크', isSelected: false },
    { id: 13, location: '도미니카 공화국', isSelected: false },
    { id: 14, location: '독일', isSelected: false },
    { id: 15, location: '라오스', isSelected: false },
    { id: 16, location: '라트비아', isSelected: false },
    { id: 17, location: '러시아', isSelected: false },
    { id: 18, location: '레바논', isSelected: false },
    { id: 19, location: '루마니아', isSelected: false },
    { id: 20, location: '룩셈부르크', isSelected: false },
    { id: 21, location: '리비아', isSelected: false },
    { id: 22, location: '리투아니아', isSelected: false },
    { id: 23, location: '리히텐슈타인', isSelected: false },
    { id: 24, location: '말레이시아', isSelected: false },
    { id: 25, location: '멕시코', isSelected: false },
    { id: 26, location: '모로코', isSelected: false },
    { id: 27, location: '몬테네그로', isSelected: false },
    { id: 28, location: '몰타', isSelected: false },
    { id: 29, location: '미국', isSelected: false },
    { id: 30, location: '바레인', isSelected: false },
    { id: 31, location: '방글라데시', isSelected: false },
    { id: 32, location: '베네수엘라', isSelected: false },
    { id: 33, location: '베트남', isSelected: false },
    { id: 34, location: '벨기에', isSelected: false },
    { id: 35, location: '벨로루시', isSelected: false },
    { id: 36, location: '보스니아-헤르체코비나', isSelected: false }, 
    { id: 37, location: '볼리비아', isSelected: false },
    { id: 38, location: '북마케도니아', isSelected: false },
    { id: 39, location: '불가리아', isSelected: false },
    { id: 40, location: '브라질', isSelected: false },
    { id: 41, location: '사우디아라비아', isSelected: false },
    { id: 42, location: '사이프러스', isSelected: false },
    { id: 43, location: '세네갈', isSelected: false },
    { id: 44, location: '세르비아', isSelected: false },
    { id: 45, location: '스리랑카', isSelected: false },
    { id: 46, location: '스웨덴', isSelected: false },
    { id: 47, location: '스위스', isSelected: false },
    { id: 48, location: '스페인', isSelected: false },
    { id: 49, location: '슬로바키아', isSelected: false },
    { id: 50, location: '슬로베니아', isSelected: false },
    { id: 51, location: '싱가포르', isSelected: false },
    { id: 52, location: '아랍 에미레이트', isSelected: false },
    { id: 53, location: '아르헨티나', isSelected: false },
    { id: 54, location: '아이슬란드', isSelected: false },
    { id: 55, location: '아일랜드', isSelected: false },
    { id: 56, location: '아제르바이잔', isSelected: false },
    { id: 57, location: '알제리', isSelected: false },
    { id: 58, location: '에스토니아', isSelected: false },
    { id: 59, location: '에콰도르', isSelected: false },
    { id: 60, location: '엘살바도르', isSelected: false },
    { id: 61, location: '영국', isSelected: false },
    { id: 62, location: '예멘', isSelected: false },
    { id: 63, location: '오만', isSelected: false },
    { id: 64, location: '오스트리아', isSelected: false },
    { id: 65, location: '온두라스', isSelected: false },
    { id: 66, location: '요르단', isSelected: false },
    { id: 67, location: '우간다', isSelected: false },
    { id: 68, location: '우루과이', isSelected: false },
    { id: 69, location: '우크라이나', isSelected: false },
    { id: 70, location: '이라크', isSelected: false },
    { id: 71, location: '이스라엘', isSelected: false },
    { id: 72, location: '이집트', isSelected: false },
    { id: 73, location: '이탈리아', isSelected: false },
    { id: 74, location: '인도', isSelected: false },
    { id: 75, location: '인도네시아', isSelected: false },
    { id: 76, location: '일본', isSelected: false },
    { id: 77, location: '자메이카', isSelected: false },
    { id: 78, location: '짐바브웨', isSelected: false },
    { id: 79, location: '체코', isSelected: false },
    { id: 80, location: '칠레', isSelected: false },
    { id: 81, location: '카자흐스탄', isSelected: false },
    { id: 82, location: '카타르', isSelected: false },
    { id: 83, location: '캄보디아', isSelected: false },
    { id: 84, location: '캐나다', isSelected: false },
    { id: 85, location: '케냐', isSelected: false },
    { id: 86, location: '코스타리카', isSelected: false },
    { id: 87, location: '콜롬비아', isSelected: false },
    { id: 88, location: '쿠웨이트', isSelected: false },
    { id: 89, location: '크로아티아', isSelected: false },
    { id: 90, location: '탄자니아', isSelected: false },
    { id: 91, location: '태국', isSelected: false },
    { id: 92, location: '터키', isSelected: false },
    { id: 93, location: '튀니지', isSelected: false },
    { id: 94, location: '파나마', isSelected: false },
    { id: 95, location: '파라과이', isSelected: false },
    { id: 96, location: '파키스탄', isSelected: false },
    { id: 97, location: '파푸아 뉴기니', isSelected: false }, 
    { id: 98, location: '페루', isSelected: false },
    { id: 99, location: '포르투갈', isSelected: false },
    { id: 100, location: '폴란드', isSelected: false },
    { id: 101, location: '푸에르토리코', isSelected: false },
    { id: 102, location: '프랑스', isSelected: false },
    { id: 103, location: '핀란드', isSelected: false },
    { id: 104, location: '필리핀', isSelected: false },
    { id: 105, location: '한국', isSelected: false },
    { id: 106, location: '헝가리', isSelected: false },
    { id: 107, location: '호주', isSelected: false },
    { id: 108, location: '홍콩', isSelected: false },
  ]
}

const location = createSlice({
  name: '위치 선택',
  initialState: locations,
  reducers: {
    changeLocation(state, action) {
      state.selected = action.payload.location
    }
  }
});

export let { changeLocation } = location.actions;
export default location;

